### ISSUE TITLE
Failed to run on mobian PP

### ISSUE THREAD

**Issue by petrisch** [chefe/sbb#2]
Hei cool app!

I got it to run on x86 debian bookworm, but failed on the PP with this:
``
error: could not compile `gtk`

Caused by:
  process didn't exit successfully: `rustc --crate-name gtk /home/mobian/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.9.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="v3_16"' --cfg 'feature="v3_18"' --cfg 'feature="v3_20"' --cfg 'feature="v3_22"' --cfg 'feature="v3_22_20"' --cfg 'feature="v3_22_26"' --cfg 'feature="v3_22_27"' --cfg 'feature="v3_22_29"' --cfg 'feature="v3_22_30"' --cfg 'feature="v3_24"' -C metadata=ee1099dfefa218c1 -C extra-filename=-ee1099dfefa218c1 --out-dir /home/mobian/Repo/sbb/target/debug/deps -L dependency=/home/mobian/Repo/sbb/target/debug/deps --extern atk=/home/mobian/Repo/sbb/target/debug/deps/libatk-2dad9d975e79e74e.rmeta --extern bitflags=/home/mobian/Repo/sbb/target/debug/deps/libbitflags-d0e09a541b23a29d.rmeta --extern cairo=/home/mobian/Repo/sbb/target/debug/deps/libcairo-a80a1df8713bc267.rmeta --extern cairo_sys=/home/mobian/Repo/sbb/target/debug/deps/libcairo_sys-efd7af3af28093c7.rmeta --extern gdk=/home/mobian/Repo/sbb/target/debug/deps/libgdk-b78978a4990baefb.rmeta --extern gdk_pixbuf=/home/mobian/Repo/sbb/target/debug/deps/libgdk_pixbuf-de5da3f7890f0278.rmeta --extern gdk_pixbuf_sys=/home/mobian/Repo/sbb/target/debug/deps/libgdk_pixbuf_sys-253b433bc840a711.rmeta --extern gdk_sys=/home/mobian/Repo/sbb/target/debug/deps/libgdk_sys-9f07d6788df0a8fc.rmeta --extern gio=/home/mobian/Repo/sbb/target/debug/deps/libgio-8890f3c0828418a8.rmeta --extern gio_sys=/home/mobian/Repo/sbb/target/debug/deps/libgio_sys-047b5e683ada982d.rmeta --extern glib=/home/mobian/Repo/sbb/target/debug/deps/libglib-2e37fb4c140562b0.rmeta --extern glib_sys=/home/mobian/Repo/sbb/target/debug/deps/libglib_sys-467c1ffa55c1d25f.rmeta --extern gobject_sys=/home/mobian/Repo/sbb/target/debug/deps/libgobject_sys-520666f67052989e.rmeta --extern gtk_sys=/home/mobian/Repo/sbb/target/debug/deps/libgtk_sys-c290c0ce91ff1db6.rmeta --extern libc=/home/mobian/Repo/sbb/target/debug/deps/liblibc-bb3e63c92db99aa8.rmeta --extern once_cell=/home/mobian/Repo/sbb/target/debug/deps/libonce_cell-e125e9482be7217d.rmeta --extern pango=/home/mobian/Repo/sbb/target/debug/deps/libpango-79ebcaf7d56114e3.rmeta --extern pango_sys=/home/mobian/Repo/sbb/target/debug/deps/libpango_sys-c812c7ac48ee4d08.rmeta --cap-lints allow --cfg 'gdk_backend="x11"' --cfg 'gdk_backend="broadway"' --cfg 'gdk_backend="wayland"'` (signal: 9, SIGKILL: kill)
``

**Comment by chefe** [comment]
I tried to compile the app today on a pinephone with mobian and it worked just fine. I was using the following versions:

```
$ uname -rs
Linux 5.10-sunxi64
$ cat /etc/debian_version
11.2
$ rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)
```

If you have issues with the native version, you can can try the flatpak version.

**Comment by petrisch** [comment]
Hm, now it works, strange.
all I did differently was not to do it over ssh.
Maybe something with the user config, that I'm not aware of.
But it works like a charm now, thank you very much. One ore thing I can do on this platform!
Whats your general plan? GTK4 once its more stable?

**Comment by chefe** [comment]
Glade that it works for you now. Yes, a rewrite with gtk4 is generally the goal but there is no schedule yet.
